language: scala
jdk:
- oraclejdk9
scala:
- 2.12.6
sudo: required
branches:
  only:
    - master
    - /^\d\.\d+$/
services:
  - docker
before_install:
  - docker build -t scrypto:test .
script:
  - sbt test:compile
  - docker run --rm -it scrypto:test sbt test
